doulaap/urls.py
from django.conf.urls import patterns, url, include
from django.conf import settings

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    #(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^grappelli/', include('grappelli.urls')),
    (r'^admin/', include(admin.site.urls)),

    # Demo Override the signup form with our own, which includes a
    # first and last name.
    # (r'^accounts/signup/$',
    #  'userena.views.signup',
    #  {'signup_form': SignupFormExtra}),

    (r'^accounts/', include('userena.urls')),
    (r'^messages/', include('userena.contrib.umessages.urls')),
    url(r'^$', 'profiles.views.promo', name='promo'),
    url(r'^howitworks/$', 'profiles.views.howitworks', name='howitworks'),
    url(r'^aboutus/$', 'profiles.views.aboutus', name='aboutus'),
    url(r'^testimonial/$', 'profiles.views.testimonial', name='testimonial'),
    url(r'^privacy/$', 'profiles.views.privacy', name='privacy'),
    url(r'^terms/$', 'profiles.views.terms', name='terms'),
    (r'^i18n/', include('django.conf.urls.i18n')),



    #url(r'^admin/', include(admin.site.urls)),
    #url(r'^$', TemplateView.as_view(template_name="index.html")),
    #url(r'^auth/$', TemplateView.as_view(template_name="login.html")),
    #url(r'^auth/register$', 'auth.views.register'),
    #url(r'^auth/create_user$', 'auth.views.create_user'),
    #url(r'^auth/login$', 'auth.views.__login'),
    #url(r'^auth/logout$', 'auth.views._logout'),
    #url(r'^auth/_login$', 'auth.views._login'),
    url(r'^donation/(?P<id>[0-9]+)/$', 'donation.views.charge'),
    url(r'^donate/(?P<id>[0-9]+)/$', 'donation.views.first_step'),
    url(r'^doula/$', 'project.views.show_projects', name='project'),
    url(r'^doula/save_comment', 'project.views._comment'),
    url(r'^doula/show/(?P<id>[0-9]+)/$', 'project.views.show_project_page', name='show_project_page'),
    url(r'^doula/profile$', 'doulaprofile.views.doulaprofile_list', name='doulaprofile_list'),
    url(r'^doula/profile/(?P<id>[0-9]+)/$', 'doulaprofile.views.doulaprofile', name='doulaprofile'),
    url(r'^doula/profile/create$', 'doulaprofile.views.doulaprofile_create', name='doulaprofile_create'),
    url(r'^doula/profile/edit$', 'doulaprofile.views.doulaprofile_edit', name='doulaprofile_edit'),
    url(r'^doula/create$', 'project.views.save_project', name='create_project'),
    url(r'^doula/save_project$', 'project.views.save_project'),
    url(r'^doula/pledge$', 'project.views.pledge'),
    url(r'^doula/save_pledge$', 'project.views._pledge'),
    url(r'^doula/save_comment', 'project.views._comment'),
    url(r'^doula/save_update', 'project.views._update'),
    url(r'^doula/confirm_project/(?P<id>[0-9]+)/$', 'project.views._confirm_project'),
    #url(r'^profile/(?P<uid>[0-9]+)$', 'auth.views.profile', name='profile'),


)

# Add media and static files
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userena/runtests/urls.py
from django.conf.urls import patterns, url, include
from django.conf import settings

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/', include(admin.site.urls)),

    # Demo Override the signup form with our own, which includes a
    # first and last name.
    # (r'^accounts/signup/$',
    #  'userena.views.signup',
    #  {'signup_form': SignupFormExtra}),

    (r'^accounts/', include('userena.urls')),
    (r'^messages/', include('userena.contrib.umessages.urls')),
    (r'^i18n/', include('django.conf.urls.i18n')),
)

# Add media and static files
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userena/urls.py
from django.conf.urls import *
from django.contrib.auth import views as auth_views

from userena import views as userena_views
from userena import settings as userena_settings
from userena.compat import auth_views_compat_quirks, password_reset_uid_kwarg


def merged_dict(dict_a, dict_b):
    """Merges two dicts and returns output. It's purpose is to ease use of
    ``auth_views_compat_quirks``
    """
    dict_a.update(dict_b)
    return dict_a

urlpatterns = patterns('',
    # Signup, signin and signout
    url(r'^signup/$',
       userena_views.signup,
       name='userena_signup'),
    url(r'^signin/$',
       userena_views.signin,
       name='userena_signin'),
    url(r'^signout/$',
       userena_views.signout,
       name='userena_signout'),

    # Reset password
    url(r'^password/reset/$',
       auth_views.password_reset,
       merged_dict({'template_name': 'userena/password_reset_form.html',
                    'email_template_name': 'userena/emails/password_reset_message.txt',
                    'extra_context': {'without_usernames': userena_settings.USERENA_WITHOUT_USERNAMES}
                   }, auth_views_compat_quirks['userena_password_reset']),
       name='userena_password_reset'),
    url(r'^password/reset/done/$',
       auth_views.password_reset_done,
       {'template_name': 'userena/password_reset_done.html',},
       name='userena_password_reset_done'),
    url(r'^password/reset/confirm/(?P<%s>[0-9A-Za-z]+)-(?P<token>.+)/$' % password_reset_uid_kwarg,
       auth_views.password_reset_confirm,
       merged_dict({'template_name': 'userena/password_reset_confirm_form.html',
                    }, auth_views_compat_quirks['userena_password_reset_confirm']),
       name='userena_password_reset_confirm'),
    url(r'^password/reset/confirm/complete/$',
       auth_views.password_reset_complete,
       {'template_name': 'userena/password_reset_complete.html'},
        name='userena_password_reset_complete'),

    # Signup
    url(r'^(?P<username>[\.\w-]+)/signup/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/signup_complete.html',
        'extra_context': {'userena_activation_required': userena_settings.USERENA_ACTIVATION_REQUIRED,
                          'userena_activation_days': userena_settings.USERENA_ACTIVATION_DAYS}},
       name='userena_signup_complete'),

    # Activate
    url(r'^activate/(?P<activation_key>\w+)/$',
       userena_views.activate,
       name='userena_activate'),

    # Retry activation
    url(r'^activate/retry/(?P<activation_key>\w+)/$',
        userena_views.activate_retry,
        name='userena_activate_retry'),

    # Change email and confirm it
    url(r'^(?P<username>[\.\w-]+)/email/$',
       userena_views.email_change,
       name='userena_email_change'),
    url(r'^(?P<username>[\.\w-]+)/email/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/email_change_complete.html'},
       name='userena_email_change_complete'),
    url(r'^(?P<username>[\.\w-]+)/confirm-email/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/email_confirm_complete.html'},
       name='userena_email_confirm_complete'),
    url(r'^confirm-email/(?P<confirmation_key>\w+)/$',
       userena_views.email_confirm,
       name='userena_email_confirm'),

    # Disabled account
    url(r'^(?P<username>[\.\w-]+)/disabled/$',
       userena_views.disabled_account,
       {'template_name': 'userena/disabled.html'},
       name='userena_disabled'),

    # Change password
    url(r'^(?P<username>[\.\w-]+)/password/$',
       userena_views.password_change,
       name='userena_password_change'),
    url(r'^(?P<username>[\.\w-]+)/password/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/password_complete.html'},
       name='userena_password_change_complete'),

    # Edit profile
    url(r'^(?P<username>[\.\w-]+)/edit/$',
       userena_views.profile_edit,
       name='userena_profile_edit'),

    # View profiles
    url(r'^(?P<username>(?!signout|signup|signin)[\.\w-]+)/$',
       userena_views.profile_detail,
       name='userena_profile_detail'),
    url(r'^page/(?P<page>[0-9]+)/$',
       userena_views.ProfileListView.as_view(),
       name='userena_profile_list_paginated'),
    url(r'^$',
       userena_views.ProfileListView.as_view(),
       name='userena_profile_list'),
)

project/models.py
from django.db import models
from time import time
from datetime import datetime, timedelta

def get_upload_file_name(instance, filename):
    return "uploaded_files/%s_%s" % (str(time()).replace('.', '_'), filename)


class ProjectManager(models.Manager):
    def create_project(self, title, story, fundamount, days):
        project = self.create(title=title, our_story=story, funding_amount=fundamount, days_req=days)
        return project


class Project(models.Model):
    #project_id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=4000)
    our_story = models.CharField(max_length=4000)
    img_link = models.FileField('Add Photo', upload_to=get_upload_file_name)
    #img_link2 = models.FileField('Add Photo', upload_to=get_upload_file_name, blank=True)
    #img_link3 = models.FileField('Add Photo', upload_to=get_upload_file_name, blank=True)
    #img_link4 = models.FileField('Add Photo', upload_to=get_upload_file_name, blank=True)
    why_want_doula = models.CharField('Why we need doula', max_length=4000)
    our_doula = models.CharField(max_length=4000)
    funding_amount = models.IntegerField(default=1)
    misc = models.CharField('Miscellaneous', max_length=4000)
    link_fb = models.CharField('Facebok', max_length=4000, blank=True)
    link_tw = models.CharField('Twitter', max_length=4000, blank=True)
    link_inst = models.CharField('Instagram', max_length=4000, blank=True)
    days_req = models.IntegerField(default=60)
    is_review = models.BooleanField('Confirm', default=False)
    totalpledgers = models.IntegerField(default=0)
    totalpledgeamount = models.IntegerField(default=0)
    userid = models.IntegerField('User ID', default=0)
    startdate = models.DateTimeField(auto_now_add=True)
    expdate = models.DateTimeField('Expiration Date', default=datetime.now()+timedelta(days=60))
    objects = ProjectManager()


class PledgeManager(models.Manager):
    def pledge(self, userid, projectid, amount, comments):
        pledge = self.create(user_id=userid, project_id=projectid, amount_pledged=amount, comments=comments)
        return pledge


class Pledgers(models.Model):
    #pid = models.AutoField(primary_key=True)
    user_id = models.IntegerField(default=1)
    username = models.CharField(max_length=200, blank=True)
    email = models.CharField(max_length=200, blank=True)
    project = models.ForeignKey(Project)
    amount_pledged = models.IntegerField(default=0)
    comments = models.CharField(max_length=4000, blank=True)
    datecreated = models.DateTimeField(auto_now_add=True)
    objects = PledgeManager()


class CommentManager(models.Manager):
    def comments(self, uid, projectid, comments):
        comments = self.create(user_id=uid, project_id=projectid, comments=comments)
        return comments


class Comment(models.Model):
    #pid = models.AutoField(primary_key=True)
    user_id = models.IntegerField(default=0)
    #project_id = models.IntegerField(default=0)
    project = models.ForeignKey(Project)
    comments = models.CharField(max_length=4000)
    datecreated = models.DateTimeField(auto_now_add=True)
    objects = CommentManager()


class UpdateManager(models.Manager):
    def updates(self, uid, projectid, updates):
        updates = self.create(user_id=uid, project_id=projectid, updates=updates)
        return updates


class Update(models.Model):
    #pid = models.AutoField(primary_key=True)
    user_id = models.IntegerField(default=0)
    #project_id = models.IntegerField(default=0)
    project = models.ForeignKey(Project)
    updates = models.CharField(max_length=4000)
    datecreated = models.DateTimeField(auto_now_add=True)
    objects = UpdateManager()

project/forms.py
from models import Project
from django import forms


class ProjectForm(forms.ModelForm):
    #title = forms.CharField(required=True)
    #our_story = forms.CharField(required=True)
    #img_link = forms.FileField(required=True)
    #why_want_doula = forms.CharField(required=True)
    #our_doula = forms.CharField(required=True)
    #funding_amount = forms.IntegerField(required=True)
    #misc = forms.CharField(required=True)
    #link_fb = forms.CharField(required=False)
    #link_tw = forms.CharField(required=False)
    #link_inst = forms.CharField(required=False)
    #days_req = forms.IntegerField(required=True)
    #userid = forms.IntegerField(required=True)

    class Meta:
        model = Project
        fields = ('title','our_story','img_link','why_want_doula','our_doula','funding_amount', 'days_req', 'userid')

project/templates/create.html
{% extends "base.html" %}
{% load url from future %}
{% block content %}

        {% if messages %}
            <div class="alert alert-info">
                {% for message in messages %}
                    <a href="#" class="close" data-dismiss="alert">&times;</a>
                {{ message }}
                {% endfor %}
            </div>
        {% endif %}


<section id="form-section" style="padding: 20px 0px;">
    <div class="form-wrap">
      <h1 class="h1">Create Doula Fundraiser</h1>
      <div class="box">

{%if user.is_authenticated%}


       <form name="createDoula" onsubmit="return(validateDoulaForm());" role="form" action="{{BASE_URL}}/doula/save_project" method="post" enctype="multipart/form-data">
            <fieldset>
            {% csrf_token %}

                <!--
                {{form.as_ul}}
                -->

            <input  id="id_userid" name="userid" type="hidden" value="{{user.id}}">
            <input  id="id_days_req" name="days_req" type="hidden" value="60">

            <div class="form-group clearfix">
            <div class="col-md-12">
              <label for="id_title">* Title</label> <span style="float: right;" id="title_error"></span>
              <input  id="id_title" name="title" class="form-control" type="text" placeholder="Project Title">
            </div>
          </div>

          <div class="form-group clearfix">
            <div class="col-md-12">
              <label for="id_our_story">* Our Story</label><span style="float: right;" id="our_story_error"></span>
              <textarea  id="id_our_story" name="our_story" cols="30" rows="4" class="form-control" placeholder="Our story..."></textarea>
            </div>
          </div>

          <div class="form-group clearfix">
            <div class="col-md-12">
              <label for="id_img_link">* Upload any relevant photo</label><span style="float: right;" id="img_link_error"></span>
              <input type="file" id="id_img_link" name="img_link" required="">
            </div>
          </div>

          <div class="form-group clearfix">
            <div class="col-md-12">
              <label for="id_why_want_doula">* Why we want a Doula</label><span style="float: right;" id="why_want_doula_error"></span>
              <textarea  id="id_why_want_doula" name="why_want_doula" cols="30" rows="4" placeholder="" class="form-control"></textarea>
            </div>
          </div>

          <div class="form-group clearfix">
            <div class="col-md-12">
              <label for="id_our_doula">* Our Doula</label><span style="float: right;" id="our_doula_error"></span>
              <textarea id="id_our_doula" name="our_doula" cols="30" rows="4" placeholder="Our Doula" class="form-control"></textarea>
            </div>
          </div>

          <div class="form-group clearfix">
            <div class="col-md-12">
              <label for="id_funding_amount">* Funding Amount Needed</label><span style="float: right;" id="funding_amount_error"></span>
              <input  id="id_funding_amount" name="funding_amount" type="text" placeholder="$0.00 USD" class="form-control">
            </div>
          </div>

<!--
          <div class="form-group clearfix">
            <div class="col-md-12">
              <label for="id_misc">Misc (What you type here will be visible to site admin)</label><span style="float: right;" id="misc_error"></span>
              <input  id="id_misc" name="misc" type="text" placeholder="" class="form-control">
            </div>
          </div>
-->
          <div class="form-group clearfix">
            <div class="col-md-12">
              <label for="id_link_fb">Link to your Facebook page (optional)</label><span style="float: right;" id="link_fb_error"></span>
              <input  id="id_link_fb" name="link_fb" type="text" placeholder="" class="form-control">
            </div>
          </div>

          <div class="form-group clearfix">
            <div class="col-md-12">
              <label for="id_link_tw">Link to your Twitter (optional)</label><span style="float: right;" id="link_tw_error"></span>
              <input  id="id_link_tw" name="link_tw" type="text" placeholder="" class="form-control">
            </div>
          </div>

          <div class="form-group clearfix">
            <div class="col-md-12">
              <label for="id_link_inst">Link to your Instagram (optional)</label><span style="float: right;" id="link_inst_error"></span>
              <input  id="id_link_inst" name="link_inst" type="text" placeholder="" class="form-control">
            </div>
          </div>

          <div class="form-group clearfix">
            <div class="col-md-12">
              <button type="submit" class="btn btn-primary btn-green btn-lg">Create Doula Fundraiser</button>
            </div>
          </div>

            </fieldset>
        </form>


{%else%}

    <p>You must be <a href="{% url 'userena_signin' %}">Sign in</a> to create a Doula.</p>

{%endif%}

      </div>
    </div>
</section>

{% endblock %}

project/templates/pledge.html
<!DOCTYPE html>
<html lang="en-us">
<head>
  <meta http-equiv="X-UA-Compatible" content="IE=Edge">
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Merlin HTML/CSS template">
  <meta name="author" content="Hasan Alibegic">
  <link rel="shortcut icon" href="{{STATIC_URL}}ico/favicon.ico">
  <title>Project</title>
  <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:300,600">
  <link rel="stylesheet" href="{{STATIC_URL}}css/bootstrap.min.css">
  <link rel="stylesheet" href="{{STATIC_URL}}css/style.css">
  <link rel="stylesheet" href="{{STATIC_URL}}css/facebookimages.css">
  <link rel="stylesheet" href="{{STATIC_URL}}css/animate.min.css">
  <link rel="stylesheet" href="{{STATIC_URL}}css/font-awesome.min.css">
    <!--[if lt IE 9]>
    <script src="{{STATIC_URL}}js/html5shiv.js"></script>
    <script src="{{STATIC_URL}}js/respond.min.js"></script>
    <![endif]-->
  </head>
    <body>
      <div id="navbar-top">
        <nav class="navbar navbar-default navbar-static" role="navigation">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand nav-external" href="#home"></a>
            </div>
            <div class="collapse navbar-collapse">
              <ul class="nav navbar-nav navbar-right">
                <li>
                  <a href="{{BASE_URL}}">Home</a>
                </li>
              </ul>
            </div>
          </div>
        </nav>
      </div>
      <div class="container-fluid">

        <div class="row">
        {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
{%if user.is_authenticated%}
        <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
        <form class="form-horizontal" method="POST" action="{{BASE_URL}}/project/pledge_project">{% csrf_token %}
<center><h1 style="margin-top:5px;">Pledge Project</h1></center>
<!-- Text input-->
<div class="form-group">
  <label class="control-label" for="project_name">Project Name</label>
  <div class="controls">
    <input class="form-control" id="project_name" name="project_name" type="text" placeholder="Taco Bell" class="input-xlarge" required="">
    
  </div>
</div>
<!-- Textarea -->
<div class="form-group">
  <label class="control-label" for="project_desc">One Line Project Description</label>
  <div class="controls">                     
    <textarea class="form-control" id="project_desc" name="project_desc">My project is about....</textarea>
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="control-label" for="money_req">Money Required</label>
  <div class="controls">
    <input class="form-control" id="money_req" name="money_req" type="text" placeholder="$$$$" class="input-medium">
    
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="control-label" for="days_req">Days required</label>
  <div class="controls">
    <input class="form-control" id="days_req" name="days_req" type="text" placeholder="" class="input-medium">
    
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="control-label" for="img_link">Link to image:</label>
  <div class="controls">
    <input class="form-control" id="img_link" name="img_link" type="text" placeholder="https://www.example.com/image.jpg" class="input-xlarge" required="">
    
  </div>
</div>
<!-- Text input-->
<div class="form-group">
  <label class="control-label" for="video_link">Link to video:</label>
  <div class="controls">
    <input class="form-control" id="video_link" name="video_link" type="text" placeholder="https://www.example.com/video.mp4" class="input-xlarge" required="">
    
  </div>
</div>

<!-- Textarea -->
<div class="form-group">
  <label class="control-label" for="details">Detailed Explanation:</label>
  <div class="controls">                     
    <textarea id="details" name="details" class="form-control"></textarea>
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="control-label" for="project_use">Project Use:</label>
  <div class="controls">
    <input class="form-control" id="project_use" name="project_use" type="text" placeholder="" class="input-xlarge" required="">
    
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="control-label" for="pledge2">Pledge Amount 1:</label>
  <div class="controls">
    <input class="form-control" id="pledge2" name="pledge2" type="text" placeholder="" class="input-xlarge" required="">
    
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="control-label" for="pledge1">Pledge Amount 2:</label>
  <div class="controls">
    <input class="form-control" id="pledge1" name="pledge1" type="text" placeholder="" class="input-xlarge" required="">
    
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="control-label" for="pledge3">Pledge Amount 3:</label>
  <div class="controls">
    <input class="form-control" id="pledge3" name="pledge3" type="text" placeholder="" class="input-xlarge" required="">
    
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="control-label" for="pledge4">Pledge Amount 4:</label>
  <div class="controls">
    <input class="form-control" id="pledge4" name="pledge4" type="text" placeholder="" class="input-xlarge" required="">
    
  </div>
</div>

<!-- Button -->
<div class="form-group">
  <label class="control-label" for="submit"></label>
  <div class="controls">
    <button id="submit" name="submit" class="btn btn-success">Submit</button>
  </div>
</div>

</fieldset>
</form>
</div>
        </div>
      </div>
      {%else%}
      <div class="jumbotron">
        <p class="lead">You must be logged in to create a project.</p>
      </div>
{%endif%}

    <script src="{{STATIC_URL}}js/jquery.min.js"></script>
    <script src="{{STATIC_URL}}js/bootstrap.min.js"></script>
    <script src="{{STATIC_URL}}js/isotope.pkgd.min.js"></script>
    <script src="{{STATIC_URL}}js/imagesloaded.min.js"></script>
    <script src="{{STATIC_URL}}js/jquery.scrollTo.min.js"></script>
    <script src="{{STATIC_URL}}js/jquery.nav.min.js"></script>
    <script src="{{STATIC_URL}}js/jquery.appear.min.js"></script>
    <script src="{{STATIC_URL}}js/twitterFetcher.min.js"></script>
    <script src="{{STATIC_URL}}js/script.js"></script>

  </body>
  </html>

project/templates/project (copy).html
{% extends "base.html" %}
{% load url from future %}
{% load humanize %}
{% block content %}

        {% if messages %}
            <div class="alert alert-info">
                {% for message in messages %}
                    <a href="#" class="close" data-dismiss="alert">&times;</a>
                {{ message }}
                {% endfor %}
            </div>
        {% endif %}

<section id="trending">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div id="owl-demo">

            {%if project%}
                {%for item in project%}
                    {% if user.is_authenticated and user.id == 1 %}


                        <div class="item">
                          <div class="fundraiser-entry clearfix">
                            <a href="{{BASE_URL}}/doula/show/{{item.id}}"><img src="/media/{{item.img_link}}" alt="Image"></a>
                            <div class="fundraiser-intro-wrap">
                              <h3><a href="{{BASE_URL}}/doula/show/{{item.id}}">{{item.title}}</a></h3>
                              <p>{{item.project_desc}}</p>
                              <div class="fundraiser-stat">
                                <div class="money-raised"><strong>${{ item.totalpledgeamount|floatformat:2|intcomma }}</strong> <span>USD</span></div>
                                <div class="fundraiser-progress progress">
                                  <div class="progress-bar" role="progressbar" aria-valuenow="{{item.percent}}" aria-valuemin="0" aria-valuemax="100" style="width: {{item.percent}}%;">
                                    <span class="sr-only">{{item.percent}}</span>
                                  </div>
                                </div>
                                <div class="fundraiser-percent-daysleft clearfix">
                                  <span class="percent pull-left">{{item.percent}}%</span>
                                  <span class="daysleft pull-right"> {{ item.expd }} days left</span>
                                </div>

                                {% if item.is_review == 0 %}
                                  <a href="{{BASE_URL}}/doula/confirm_project/{{item.pk}}" class="pull-right ghost-btn-white trending-btn" style="margin-bottom: 10px;">Confirm doula</a>
                                {% endif %}


                              </div>
                            </div>
                          </div>
                        </div>
                        <!-- /item -->



                    {% else %}
                        {% if item.is_review %}


                            <div class="item">
                              <div class="fundraiser-entry clearfix">
                                <a href="{{BASE_URL}}/doula/show/{{item.id}}"><img src="/media/{{item.img_link}}" alt="Image"></a>
                                <div class="fundraiser-intro-wrap">
                                  <h3><a href="{{BASE_URL}}/doula/show/{{item.id}}">{{item.title}}</a></h3>
                                  <p>{{item.project_desc}}</p>
                                  <div class="fundraiser-stat">
                                    <div class="money-raised"><strong>${{ item.totalpledgeamount|floatformat:2|intcomma }}</strong> <span>USD</span></div>
                                    <div class="fundraiser-progress progress">
                                      <div class="progress-bar" role="progressbar" aria-valuenow="{{item.percent}}" aria-valuemin="0" aria-valuemax="100" style="width: {{item.percent}}%;">
                                        <span class="sr-only">{{item.percent}}</span>
                                      </div>
                                    </div>
                                    <div class="fundraiser-percent-daysleft clearfix">
                                      <span class="percent pull-left">{{item.percent}}%</span>
                                      <span class="daysleft pull-right"> {{ item.expd }} days left</span>
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                            <!-- /item -->


                        {%endif%}
                    {%endif%}

                {%endfor%}
            {%endif%}

          </div>
          <!-- /owl-demo -->
        </div>
      </div>

    </div>
</section>

<section id="spread-the-word">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="share text-center">
            <h2>Spread The Word</h2>
            <a href="#" class="btn ghost-btn-share">Share On Twitter</a>
            <a href="#" class="btn ghost-btn-share">Share On Facebook</a>
          </div>
        </div>
      </div>
    </div>
</section>
{% endblock %}