doulaap/urls.py
from django.conf.urls import patterns, url, include
from django.conf import settings

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    #(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^grappelli/', include('grappelli.urls')),
    (r'^admin/', include(admin.site.urls)),

    # Demo Override the signup form with our own, which includes a
    # first and last name.
    # (r'^accounts/signup/$',
    #  'userena.views.signup',
    #  {'signup_form': SignupFormExtra}),

    (r'^accounts/', include('userena.urls')),
    (r'^messages/', include('userena.contrib.umessages.urls')),
    url(r'^$', 'profiles.views.promo', name='promo'),
    url(r'^howitworks/$', 'profiles.views.howitworks', name='howitworks'),
    url(r'^aboutus/$', 'profiles.views.aboutus', name='aboutus'),
    url(r'^testimonial/$', 'profiles.views.testimonial', name='testimonial'),
    url(r'^privacy/$', 'profiles.views.privacy', name='privacy'),
    url(r'^terms/$', 'profiles.views.terms', name='terms'),
    (r'^i18n/', include('django.conf.urls.i18n')),



    #url(r'^admin/', include(admin.site.urls)),
    #url(r'^$', TemplateView.as_view(template_name="index.html")),
    #url(r'^auth/$', TemplateView.as_view(template_name="login.html")),
    #url(r'^auth/register$', 'auth.views.register'),
    #url(r'^auth/create_user$', 'auth.views.create_user'),
    #url(r'^auth/login$', 'auth.views.__login'),
    #url(r'^auth/logout$', 'auth.views._logout'),
    #url(r'^auth/_login$', 'auth.views._login'),
    url(r'^donation/(?P<id>[0-9]+)/$', 'donation.views.charge'),
    url(r'^donate/(?P<id>[0-9]+)/$', 'donation.views.first_step'),
    url(r'^doula/$', 'project.views.show_projects', name='project'),
    url(r'^doula/save_comment', 'project.views._comment'),
    url(r'^doula/show/(?P<id>[0-9]+)/$', 'project.views.show_project_page', name='show_project_page'),
    url(r'^doula/profile$', 'doulaprofile.views.doulaprofile_list', name='doulaprofile_list'),
    url(r'^doula/profile/(?P<id>[0-9]+)/$', 'doulaprofile.views.doulaprofile', name='doulaprofile'),
    url(r'^doula/profile/create$', 'doulaprofile.views.doulaprofile_create', name='doulaprofile_create'),
    url(r'^doula/profile/edit$', 'doulaprofile.views.doulaprofile_edit', name='doulaprofile_edit'),
    url(r'^doula/create$', 'project.views.save_project', name='create_project'),
    url(r'^doula/save_project$', 'project.views.save_project'),
    url(r'^doula/pledge$', 'project.views.pledge'),
    url(r'^doula/save_pledge$', 'project.views._pledge'),
    url(r'^doula/save_comment', 'project.views._comment'),
    url(r'^doula/save_update', 'project.views._update'),
    url(r'^doula/confirm_project/(?P<id>[0-9]+)/$', 'project.views._confirm_project'),
    #url(r'^profile/(?P<uid>[0-9]+)$', 'auth.views.profile', name='profile'),


)

# Add media and static files
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userena/runtests/urls.py
from django.conf.urls import patterns, url, include
from django.conf import settings

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/', include(admin.site.urls)),

    # Demo Override the signup form with our own, which includes a
    # first and last name.
    # (r'^accounts/signup/$',
    #  'userena.views.signup',
    #  {'signup_form': SignupFormExtra}),

    (r'^accounts/', include('userena.urls')),
    (r'^messages/', include('userena.contrib.umessages.urls')),
    (r'^i18n/', include('django.conf.urls.i18n')),
)

# Add media and static files
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userena/urls.py
from django.conf.urls import *
from django.contrib.auth import views as auth_views

from userena import views as userena_views
from userena import settings as userena_settings
from userena.compat import auth_views_compat_quirks, password_reset_uid_kwarg


def merged_dict(dict_a, dict_b):
    """Merges two dicts and returns output. It's purpose is to ease use of
    ``auth_views_compat_quirks``
    """
    dict_a.update(dict_b)
    return dict_a

urlpatterns = patterns('',
    # Signup, signin and signout
    url(r'^signup/$',
       userena_views.signup,
       name='userena_signup'),
    url(r'^signin/$',
       userena_views.signin,
       name='userena_signin'),
    url(r'^signout/$',
       userena_views.signout,
       name='userena_signout'),

    # Reset password
    url(r'^password/reset/$',
       auth_views.password_reset,
       merged_dict({'template_name': 'userena/password_reset_form.html',
                    'email_template_name': 'userena/emails/password_reset_message.txt',
                    'extra_context': {'without_usernames': userena_settings.USERENA_WITHOUT_USERNAMES}
                   }, auth_views_compat_quirks['userena_password_reset']),
       name='userena_password_reset'),
    url(r'^password/reset/done/$',
       auth_views.password_reset_done,
       {'template_name': 'userena/password_reset_done.html',},
       name='userena_password_reset_done'),
    url(r'^password/reset/confirm/(?P<%s>[0-9A-Za-z]+)-(?P<token>.+)/$' % password_reset_uid_kwarg,
       auth_views.password_reset_confirm,
       merged_dict({'template_name': 'userena/password_reset_confirm_form.html',
                    }, auth_views_compat_quirks['userena_password_reset_confirm']),
       name='userena_password_reset_confirm'),
    url(r'^password/reset/confirm/complete/$',
       auth_views.password_reset_complete,
       {'template_name': 'userena/password_reset_complete.html'},
        name='userena_password_reset_complete'),

    # Signup
    url(r'^(?P<username>[\.\w-]+)/signup/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/signup_complete.html',
        'extra_context': {'userena_activation_required': userena_settings.USERENA_ACTIVATION_REQUIRED,
                          'userena_activation_days': userena_settings.USERENA_ACTIVATION_DAYS}},
       name='userena_signup_complete'),

    # Activate
    url(r'^activate/(?P<activation_key>\w+)/$',
       userena_views.activate,
       name='userena_activate'),

    # Retry activation
    url(r'^activate/retry/(?P<activation_key>\w+)/$',
        userena_views.activate_retry,
        name='userena_activate_retry'),

    # Change email and confirm it
    url(r'^(?P<username>[\.\w-]+)/email/$',
       userena_views.email_change,
       name='userena_email_change'),
    url(r'^(?P<username>[\.\w-]+)/email/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/email_change_complete.html'},
       name='userena_email_change_complete'),
    url(r'^(?P<username>[\.\w-]+)/confirm-email/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/email_confirm_complete.html'},
       name='userena_email_confirm_complete'),
    url(r'^confirm-email/(?P<confirmation_key>\w+)/$',
       userena_views.email_confirm,
       name='userena_email_confirm'),

    # Disabled account
    url(r'^(?P<username>[\.\w-]+)/disabled/$',
       userena_views.disabled_account,
       {'template_name': 'userena/disabled.html'},
       name='userena_disabled'),

    # Change password
    url(r'^(?P<username>[\.\w-]+)/password/$',
       userena_views.password_change,
       name='userena_password_change'),
    url(r'^(?P<username>[\.\w-]+)/password/complete/$',
       userena_views.direct_to_user_template,
       {'template_name': 'userena/password_complete.html'},
       name='userena_password_change_complete'),

    # Edit profile
    url(r'^(?P<username>[\.\w-]+)/edit/$',
       userena_views.profile_edit,
       name='userena_profile_edit'),

    # View profiles
    url(r'^(?P<username>(?!signout|signup|signin)[\.\w-]+)/$',
       userena_views.profile_detail,
       name='userena_profile_detail'),
    url(r'^page/(?P<page>[0-9]+)/$',
       userena_views.ProfileListView.as_view(),
       name='userena_profile_list_paginated'),
    url(r'^$',
       userena_views.ProfileListView.as_view(),
       name='userena_profile_list'),
)

doulaprofile/models.py
from django.db import models
from time import time
from datetime import datetime, timedelta

def get_upload_file_name(instance, filename):
    return "uploaded_files/%s_%s" % (str(time()).replace('.', '_'), filename)


class DoulaprofileManager(models.Manager):
    def create_doulaprofile(self, about_me, education, why_they_doula, testimonials):
        doulaprofile = self.create(about_me=about_me, education=education, why_they_doula=why_they_doula,
                              testimonials=testimonials)
        return doulaprofile


class Doulaprofile(models.Model):
    userid = models.IntegerField(default=0)
    about_me = models.CharField(max_length=4000)
    education = models.CharField(max_length=4000)
    bio_pic = models.FileField(upload_to=get_upload_file_name)
    why_they_doula = models.CharField(max_length=4000)
    testimonials = models.CharField(max_length=4000)
    objects = DoulaprofileManager()

doulaprofile/forms.py
from models import Doulaprofile
from django import forms


class DoulaprofileForm(forms.ModelForm):
    class Meta:
        model = Doulaprofile
        fields = ['userid', 'bio_pic']

doulaprofile/views.py
from django.shortcuts import render
from doulaprofile.models import Doulaprofile
from django.contrib import messages
from django.http import Http404,HttpResponseRedirect
from django.shortcuts import get_object_or_404, render_to_response
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.models import User
from django.template import RequestContext
from doulaprofile.forms import DoulaprofileForm


def doulaprofile_list(request):
    doulaprofile = Doulaprofile.objects.filter(userid=request.user.id)
    doulaprofiles = Doulaprofile.objects.all()
    for item in doulaprofiles:
        user = User.objects.get(id=item.userid)
        item.username = user.username
        item.first_name = user.first_name
        item.last_name = user.last_name
    return render(request, 'doulaprofile_list.html', {'doulaprofiles': doulaprofiles, 'doulaprofile': doulaprofile})


def doulaprofile(request, id):
    doulaprofile = Doulaprofile.objects.filter(userid=id)
    for item in doulaprofile:
        user = User.objects.get(id=item.userid)
        item.username = user.username
        item.first_name = user.first_name
        item.last_name = user.last_name
    return render(request, 'doulaprofile.html', {'doulaprofile': doulaprofile})


def doulaprofile_create(request):
    if request.method == "POST":
        doulaprofile = Doulaprofile.objects.create_doulaprofile(request.POST['about_me'], request.POST['education'],
                                                           request.POST['why_they_doula'], request.POST['testimonials'])
        doulaprofile.userid = request.POST['userid']
        doulaprofile.save()
        messages.info(request, 'Profile has been successfully created.')
        return HttpResponseRedirect('/doula/profile')
    else:
        form = DoulaprofileForm()

    return render(request, 'doulaprofile_create.html', {'form': form})


def doulaprofile_edit(request):
    instance = get_object_or_404(Doulaprofile, userid=request.user.id)
    if request.method == "POST":
        form = DoulaprofileForm(request.POST, request.FILES, instance=instance)
        doulapro = form.save(commit=False)
        doulapro.about_me = request.POST['about_me']
        doulapro.education = request.POST['education']
        doulapro.why_they_doula = request.POST['why_they_doula']
        doulapro.testimonials = request.POST['testimonials']
        doulapro.save()
        form.save_m2m()
        form.save()
        messages.info(request, 'Profile has been successfully updated.')
        return HttpResponseRedirect('/doula/profile/'+str(request.user.id))
    else:
        form = DoulaprofileForm(instance=instance)
        dlpro = Doulaprofile.objects.filter(userid=request.user.id)

    return render(request, 'doulaprofile_edit.html', {'form': form, 'doulapro': dlpro})

doulaprofile/templates/doulaprofile (copy).html
{% extends "base.html" %}
{% load url from future %}
{% load humanize %}
{% block content %}

        {% if messages %}
            <div class="alert alert-info">
                {% for message in messages %}
                    <a href="#" class="close" data-dismiss="alert">&times;</a>
                {{ message }}
                {% endfor %}
            </div>
        {% endif %}

<main id="main" role="main">
  <div id="doula-profile">
    <div class="container">

        {%if doulaprofile%}
            {%for item in doulaprofile%}
              <div class="row">
                <div class="col-md-8 col-md-offset-2">
                  <div class="box">
                    <div class="form-group">
                        {% if item.userid = user.id %}
                        <a href="{{BASE_URL}}/doula/profile/edit" class="btn btn-primary btn-green pull-right">Edit Profile</a>
                        {% endif %}
                      <h1 class="h1">Doulas Profile</h1>
                    </div>
                    <div class="form-group">
                      <img src="/media/{{item.bio_pic}}" alt="Image" class="img-responsive">
                    </div>
                    <div class="form-group">
                      <label class="label">About Me</label>
                      <p>{{item.about_me}}</p>
                    </div>
                    <div class="form-group">
                      <label class="label">Why they are a doula</label>
                      <p>{{item.why_they_doula}}</p>
                    </div>
                    <div class="form-group">
                      <label class="label">Education / Qualification</label>
                      <p>{{item.education}}</p>
                    </div>
                    <div class="form-group">
                      <label class="label">Testimonials</label>
                      <blockquote>
                        <p>{{item.testimonials}}</p>
                      </blockquote>
                    </div>
                  </div>
                </div>
              </div>
            {% endfor %}
        {% else %}
            <p>You want to <a href="{{BASE_URL}}/doula/profile/create">create</a> doula profiles?</p>
        {% endif %}
    </div>

  </div>

</main>

{% endblock %}

doulaprofile/templates/doulaprofile.html
{% extends "base.html" %}
{% load url from future %}
{% load humanize %}
{% block content %}


        {% if messages %}
            <div class="alert alert-info">
                {% for message in messages %}
                    <a href="#" class="close" data-dismiss="alert">&times;</a>
                {{ message }}
                {% endfor %}
            </div>
        {% endif %}

{%if doulaprofile%}
    {%for item in doulaprofile%}


        <section id="fundraiser-single">
            <div class="container">
              <div class="row">
                <div class="col-md-12">
                  <h1 class="h1">Doula Profile</h1>
                    <br/>

                </div>
              </div>
              <!-- /row -->
              <div class="row">
                <div class="col-md-8">
                  <div class="fundraiser-single-img">

                        <img src="/media/{{item.bio_pic}}" alt="Image" class="img-responsive">
                  </div>
                </div>

              </div>
              <!-- /row -->

            </div>
            <!-- /container -->
            <div id="doula-tabs">
              <div class="container">
                <div class="row">
                  <div class="col-md-8">
                    <ul class="tab-nav clearfix">
                      <li class="active"><a href="#details">Details</a></li>
                    </ul>
                    <div id="tabs-content">
                      <div class="tab-content active clearfix" rel="details">
                        <ul class="post-wrap">
                            {% if item.userid = user.id %}
                                <a href="{{BASE_URL}}/doula/profile/edit" class="btn btn-primary btn-green pull-right">Edit Profile</a>
                            {% endif %}
                            <li class="post-entry">
                                <h3 class="post-username">About Me</h3>



                                <div class="post-message">
                                    <p class="pull-left">{{item.about_me}}</p>
                                </div>
                            </li>
                            <li class="post-entry">
                                <h3 class="post-username">Why they are a doula</h3>
                                <div class="post-message">
                                    <p class="pull-left">{{item.why_they_doula}}</p>
                                </div>
                            </li>
                            <li class="post-entry">
                                <h3 class="post-username">Education / Qualification</h3>
                                <div class="post-message">
                                    <p class="pull-left">{{item.education}}</p>
                                </div>
                            </li>

                            <li class="post-entry">
                                <h3 class="post-username">Testimonials</h3>
                                <div class="post-message">
                                    <blockquote>
                                        <p>{{item.testimonials}}</p>
                                    </blockquote>
                                </div>
                            </li>

                        </ul>
                      </div>
                      </div>
                    </div>
                  </div>
                  <div class="col-md-4">

                  </div>
                </div>
                <!-- /row -->
              </div>
              <!-- /container -->
            </div>
          </section>

        <section id="spread-the-word">
            <div class="container">
              <div class="row">
                <div class="col-md-6 col-md-offset-3">
                  <div class="share text-center">
                    <h2>Spread The Word</h2>
                    <a href="#" class="btn ghost-btn-share">Share On Twitter</a>
                    <a href="#" class="btn ghost-btn-share">Share On Facebook</a>
                  </div>
                </div>
              </div>
            </div>
        </section>

    {%endfor%}
{% endif %}

{% endblock %}

doulaprofile/templates/doulaprofile_create.html
{% extends "base.html" %}
{% load url from future %}
{% block content %}

        {% if messages %}
            <div class="alert alert-info">
                {% for message in messages %}
                    <a href="#" class="close" data-dismiss="alert">&times;</a>
                {{ message }}
                {% endfor %}
            </div>
        {% endif %}


<section id="form-section" style="padding: 20px 0px;">
    <div class="form-wrap">
      <h1 class="h1">Create Doula Profile</h1>
      <div class="box">

{%if user.is_authenticated%}


       <form name="" role="form" action="{{BASE_URL}}/doula/profile/create" method="post" enctype="multipart/form-data">
            <fieldset>
            {% csrf_token %}
<!--
                {{form.as_ul}}
-->
            <input  id="id_userid" name="userid" type="hidden" value="{{user.id}}">

            <div class="form-group clearfix">
                <div class="col-md-12">
                  <label for="id_bio_pic">* Bio Photo</label><span style="float: right;" id="id_bio_pic_error"></span>
                  <input type="file" id="id_bio_pic" name="bio_pic">
                </div>
            </div>

            <div class="form-group clearfix">
                <div class="col-md-12">
                  <label for="id_about_me">* About me</label> <span style="float: right;" id="about_me_error"></span>
                  <textarea  id="id_about_me" name="about_me" cols="30" rows="4" class="form-control" placeholder=""></textarea>
                </div>
            </div>

          <div class="form-group clearfix">
            <div class="col-md-12">
              <label for="id_education">* Education</label><span style="float: right;" id="education_error"></span>
              <textarea  id="id_education" name="education" cols="30" rows="4" class="form-control" placeholder=""></textarea>
            </div>
          </div>


          <div class="form-group clearfix">
            <div class="col-md-12">
              <label for="id_why_they_doula">* Why We Want Doula</label><span style="float: right;" id="why_they_doula_error"></span>
              <textarea  id="id_why_they_doula" name="why_they_doula" cols="30" rows="4" placeholder="" class="form-control"></textarea>
            </div>
          </div>

          <div class="form-group clearfix">
            <div class="col-md-12">
              <label for="id_testimonials">* Testimonials</label><span style="float: right;" id="testimonials_error"></span>
              <textarea id="id_testimonials" name="testimonials" cols="30" rows="4" placeholder="" class="form-control"></textarea>
            </div>
          </div>

          <div class="form-group clearfix">
            <div class="col-md-12">
              <button type="submit" class="btn btn-primary btn-green btn-lg">Create Doula Profile</button>
            </div>
          </div>

            </fieldset>
        </form>


{%else%}

    <p>You must be <a href="{% url 'userena_signin' %}">Sign in</a> to create a Doula.</p>

{%endif%}

      </div>
    </div>
</section>

{% endblock %}

doulaprofile/templates/doulaprofile_edit.html
{% extends "base.html" %}
{% load url from future %}
{% block content %}

        {% if messages %}
            <div class="alert alert-info">
                {% for message in messages %}
                    <a href="#" class="close" data-dismiss="alert">&times;</a>
                {{ message }}
                {% endfor %}
            </div>
        {% endif %}


<section id="form-section" style="padding: 20px 0px;">
    <div class="form-wrap">
      <h1 class="h1">Create Doula Profile</h1>
      <div class="box">

{%if user.is_authenticated%}


       <form name="" role="form" action="{{BASE_URL}}/doula/profile/edit" method="post" enctype="multipart/form-data">
            <fieldset>
            {% csrf_token %}
<!--
                {{form.as_ul}}
-->

          {%for item in doulapro%}

            <input  id="id_userid" name="userid" type="hidden" value="{{user.id}}">

            <div class="form-group clearfix">
                <div class="col-md-12">
                  <label for="id_bio_pic">* Bio Photo</label><span style="float: right;" id="id_bio_pic_error"></span>
                  <input type="file" id="id_bio_pic" name="bio_pic">
                </div>
            </div>

            <div class="form-group clearfix">
                <div class="col-md-12">
                  <label for="id_about_me">* About me</label> <span style="float: right;" id="about_me_error"></span>
                  <textarea  id="id_about_me" name="about_me" cols="30" rows="4" class="form-control" placeholder="">{{item.about_me}}</textarea>
                </div>
            </div>

          <div class="form-group clearfix">
            <div class="col-md-12">
              <label for="id_education">* Education</label><span style="float: right;" id="education_error"></span>
              <textarea  id="id_education" name="education" cols="30" rows="4" class="form-control" placeholder="">{{item.education}}</textarea>
            </div>
          </div>


          <div class="form-group clearfix">
            <div class="col-md-12">
              <label for="id_why_they_doula">* Why We Want Doula</label><span style="float: right;" id="why_they_doula_error"></span>
              <textarea  id="id_why_they_doula" name="why_they_doula" cols="30" rows="4" placeholder="" class="form-control">{{item.why_they_doula}}</textarea>
            </div>
          </div>

          <div class="form-group clearfix">
            <div class="col-md-12">
              <label for="id_testimonials">* Testimonials</label><span style="float: right;" id="testimonials_error"></span>
              <textarea id="id_testimonials" name="testimonials" cols="30" rows="4" placeholder="" class="form-control">{{item.testimonials}}</textarea>
            </div>
          </div>

          <div class="form-group clearfix">
            <div class="col-md-12">
              <button type="submit" class="btn btn-primary btn-green btn-lg">Create Doula Profile</button>
            </div>
          </div>

          {% endfor %}
            </fieldset>
        </form>


{%else%}

    <p>You must be <a href="{% url 'userena_signin' %}">Sign in</a> to create a Doula.</p>

{%endif%}

      </div>
    </div>
</section>

{% endblock %}

doulaprofile/templates/doulaprofile_list.html
{% extends "base.html" %}
{% load url from future %}
{% load humanize %}
{% block content %}

        {% if messages %}
            <div class="alert alert-info">
                {% for message in messages %}
                    <a href="#" class="close" data-dismiss="alert">&times;</a>
                {{ message }}
                {% endfor %}
            </div>
        {% endif %}

<section id="trending">
    <div class="container">
      <div class="row">

          <p>You can find a doula near you using the search service provided by <a target="_blank" href="http://apps.dona.org/Directory/Search">DONA International.</a></p>


      </div>

    </div>
</section>

{% endblock %}

doulaprofile/templates/doulaprofile_list_org.html
{% extends "base.html" %}
{% load url from future %}
{% load humanize %}
{% block content %}

        {% if messages %}
            <div class="alert alert-info">
                {% for message in messages %}
                    <a href="#" class="close" data-dismiss="alert">&times;</a>
                {{ message }}
                {% endfor %}
            </div>
        {% endif %}

<section id="trending">
    <div class="container">
      <div class="row">

           {%if doulaprofile%}
              {%for item in doulaprofile%}
                <p>Proceed to your <a href="{{BASE_URL}}/doula/profile/{{user.id}}">doula profile.</a></p>
              {% endfor %}
            {% else %}
                <p>You want to <a href="{{BASE_URL}}/doula/profile/create">create</a> doula profile?</p>
                <p>To find a Doula near you check this <a target="_blank" href="http://www.dona.org/mothers/find_a_doula.php">link</a>.</p>

            {% endif %}


            {%if doulaprofiles%}
            <div class="form-group clearfix">
                <div class="col-md-4">
                    <h3>Doula List</h3>
                </div>
            </div>


                {%for item in doulaprofiles%}

                    <div class="col-lg-3 col-md-4 col-xs-6 col-xxs-12">
                          <div class="fundraiser-entry clearfix" style="height: 360px;">
                            <a href="{{BASE_URL}}/doula/profile/{{item.userid}}" class="crop" style="background-image: url('/media/{{item.bio_pic}}')"></a>
                            <div class="fundraiser-intro-wrap">

                                <a href="{{BASE_URL}}/doula/profile/{{item.userid}}"><h3 class="post-username" style="color:#34AADC;">{{item.first_name}} {{item.last_name}}</h3></a>
                              <p style="text-align: justify;">{{item.about_me|slice:":150"}}</p>
                            </div>
                          </div>
                    </div>
<!--
                  <div class="col-lg-3 col-md-4 col-xs-6 col-xxs-12">
                    <div class="fundraiser-entry clearfix">
                    <div class="col-md-3" style="padding-top: 12px;">
                        <a href="{{BASE_URL}}/doula/profile/{{item.userid}}"><img src="/media/{{item.bio_pic}}" alt="Image" style="width: 150px;"></a>
                        <a href="{{BASE_URL}}/doula/profile/{{item.userid}}"><h3 class="post-username" style="color:#34AADC;">{{item.username}}</h3></a>
                        <p style="text-align: justify;">{{item.about_me|slice:":150"}}</p>
                    </div>
                  </div>
                  -->
                {% endfor %}
            {% endif %}

      </div>

    </div>
</section>

{% endblock %}